name: Waka Readme
on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */6 * * *"
jobs:
  update-readme:
    name: Update this repo's README
    runs-on: ubuntu-latest
    steps:
      - name: Update WakaTime README
        uses: actions/checkout@v4
      
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          TIME_RANGE: all_time
          SHOW_TOTAL: true
          CODE_LANG: rust
          STOP_AT_OTHER: true
          BLOCKS: ⣀⣄⣤⣦⣶⣷⣿
